server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true   # to see in browser http://localhost:9000/h2-console
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      show-sql: true
  application:
    name: cards
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Carter Doe - Developer"
    email: "carter@eazybank.com"
  onCallSupport:
    - (555) 555-2234
    - (555) 523-2345
